### ISSUE TITLE
Working example with S > 1

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/BayesSurvive#18]
I'm trying to create a second dataset to test the case of multiple subgroups ($S > 1$). The second subgroup is simply `simData[[2]]`, so I created the following `*_S2` objects:

```R
dataset <- list(
  "X" = simData[[1]]$X,
  "t" = simData[[1]]$time,
  "di" = simData[[1]]$status
)
dataset_2S <- list(
  dataset,
  list(
    "X" = simData[[2]]$X,
    "t" = simData[[2]]$time,
    "di" = simData[[2]]$status
  )
)

initial <- list("gamma.ini" = rep(0, ncol(dataset$X)))
initial_2S <- list(
  initial,
  list("gamma.ini" = rep(0, ncol(dataset_2S[[2]]$X)))
)

hyperparPooled = list(
  "c0"     = 2,                      # prior of baseline hazard
  "tau"    = 0.0375,                 # sd (spike) for coefficient prior
  "cb"     = 20,                     # sd (slab) for coefficient prior
  "pi.ga"  = 0.02,                   # prior variable selection probability for standard Cox models
  "a"      = -4,                     # hyperparameter in MRF prior
  "b"      = 0.1,                    # hyperparameter in MRF prior
  "G"      = simData$G               # hyperparameter in MRF prior
)
hyperparPooled_2S = list(hyperparPooled, hyperparPooled)
```

However, if I run `BayesSurvive(dataset_2S...)` I get an error regarding incorrect dimensions of the hyperparameters (both for CoxBVSSL and Sub-struct models). What would be a proper formulation for `hyperparPooled_2S`? Using `hyperparPooled` instead also doesn't work.

For an MRE, see https://gist.github.com/wleoncio/bb06f1cb937338ba2ff7fc7365769191

_Originally posted by @wleoncio in https://github.com/ocbe-uio/BayesSurvive/issues/11#issuecomment-2293370759_

**Comment by zhizuio** [comment]
As I mentioned, `hyperparPooled$G` or `hyperparPooled_2S$G` should be a block diagonal matrix in your example (https://gist.github.com/wleoncio/bb06f1cb937338ba2ff7fc7365769191), see one example in README or below:

```r
hyperparPooled$G <- Matrix::bdiag(simData$G, simData$G)
```

Also, the argument `nIter` has to be larger than `burnin`, i.e. the burn-in period has to be shorter than the whole MCMC. We can add this argument check in the very beginning of the main function `BayesSurvive()`, so that users will realise this input mistake.

**Comment by wleoncio** [comment]
Thanks, that did it! The `burnin < nIter` observation is very important, otherwise the calculation of `lp.mean` at the end of `BayesSurvive()` breaks due to invalid dimension of `beta.margin`. I'll do a quick PR for that.
